---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: supplementsapi
 namespace: default
spec:
 maxReplicas: 4
 minReplicas: 2
 scaleTargetRef:
  apiVersion: extensions/v1beta1
  kind: Deployment
  name: supplementsapi
 targetCPUUtilizationPercentage: 400 
